More flexibility in arguments for withjdk/withgraal

diff --git a/withgraal b/withgraal
--- a/withgraal
+++ b/withgraal
@@ -1,14 +1,23 @@
 #!/bin/bash -e
 
-VERSION=$1
+ARG=$1
 shift
 
-HOME_VARIABLE_NAME="GRAALVM${VERSION}_HOME"
-NEW_HOME=$(eval "echo \$${HOME_VARIABLE_NAME}")
+HOME_VARIABLE_NAME="GRAALVM${ARG}_HOME"
+PREFIXED_PATH="${HOME}/tools/java/graalvm${ARG}"
 
+NEW_HOME="${ARG}"
 if ! [ -e "$NEW_HOME" ]
 then
-	echo 1>&2 "Unsupported graalvm version: '$VERSION'. Is '$HOME_VARIABLE_NAME' defined?"
+        NEW_HOME="${PREFIXED_PATH}"
+fi
+if ! [ -e "$NEW_HOME" ]
+then
+	NEW_HOME=$(eval "echo \$${HOME_VARIABLE_NAME}")
+fi
+if ! [ -e "$NEW_HOME" ]
+then
+	echo 1>&2 "Cannot find the GraalVM install for '$ARG': '$ARG' is not a valid path, nor is '$PREFIXED_PATH', and environment variable '$HOME_VARIABLE_NAME' is not defined."
 	exit 1
 fi
 
diff --git a/withjdk b/withjdk
--- a/withjdk
+++ b/withjdk
@@ -4,16 +4,21 @@ ARG=$1
 shift
 
 HOME_VARIABLE_NAME="JAVA${ARG}_HOME"
-NEW_HOME=$(eval "echo \$${HOME_VARIABLE_NAME}")
+PREFIXED_PATH="${HOME}/tools/java/jdk${ARG}"
 
+NEW_HOME="${ARG}"
 if ! [ -e "$NEW_HOME" ]
 then
-	NEW_HOME="${ARG}"
+        NEW_HOME="${PREFIXED_PATH}"
 fi
 if ! [ -e "$NEW_HOME" ]
 then
-	echo 1>&2 "Cannot find the JDK for '$ARG': environment variable '$HOME_VARIABLE_NAME' is not defined, and '$ARG' is not a valid path."
-	exit 1
+        NEW_HOME=$(eval "echo \$${HOME_VARIABLE_NAME}")
+fi
+if ! [ -e "$NEW_HOME" ]
+then
+        echo 1>&2 "Cannot find the JDK install for '$ARG': '$ARG' is not a valid path, nor is '$PREFIXED_PATH', and environment variable '$HOME_VARIABLE_NAME' is not defined."
+        exit 1
 fi
 
 echo 1>&2 "Java Home: $NEW_HOME"
